### ISSUE TITLE
Illegal state: empty cluster in k-means

### ISSUE THREAD

**Issue by schienstockd** [tristan-mcrae-rochester/Multiphoton-Image-Analysis#1]
Hello,

I am trying your Spectral unmixing (LUMoS) in ImageJ.

I have a two-photon live-cell imaging timecourse in 3D. I have 4 fluorophores and try to unmix the sample by detecting 4 clusters.

I keep getting the following error message:

`[ERROR] Module threw exception
org.apache.commons.math4.exception.ConvergenceException: illegal state: empty cluster in k-means
	at org.apache.commons.math4.ml.clustering.KMeansPlusPlusClusterer.getPointFromLargestVarianceCluster(KMeansPlusPlusClusterer.java:440)
	at org.apache.commons.math4.ml.clustering.KMeansPlusPlusClusterer.cluster(KMeansPlusPlusClusterer.java:225)
	at com.mycompany.imagej.LUMoS_Spectral_Unmixing.run(LUMoS_Spectral_Unmixing.java:444)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by TardisBlue2** [comment]
Did you solve this problem? I got this error too

**Comment by schienstockd** [comment]
No ... Gave up on it. But it would be useful to have to clean up images.

**Comment by khoroshyy** [comment]
Replicate #1
[ERROR] Command errored: LUMoS Spectral Unmixing
org.apache.commons.math4.exception.ConvergenceException: illegal state: empty cluster in k-means
	at org.apache.commons.math4.ml.clustering.KMeansPlusPlusClusterer.getPointFromLargestVarianceCluster(KMeansPlusPlusClusterer.java:440)
	at org.apache.commons.math4.ml.clustering.KMeansPlusPlusClusterer.cluster(KMeansPlusPlusClusterer.java:225)
	at com.mycompany.imagej.K_Means.run(K_Means.java:444)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
I get this one
